sources:
  - type: git
    repo: https://github.com/nuxt/nuxt.git
    subpath: docs
    destination: nuxt

  - type: git
    repo: https://github.com/nitrojs/nitro.git
    subpath: docs
    destination: nitro
    exclude:
      - "pnpm-lock.yaml"

  - type: git
    repo: https://github.com/nuxt/ui.git
    subpath: docs/content
    destination: nuxt-ui

  - type: git
    repo: https://github.com/nuxt/content.git
    subpath: docs/content
    destination: nuxt-content

  - type: git
    repo: https://github.com/odoo/documentation.git
    destination: odoo

  - type: http
    url: https://raw.githubusercontent.com/adomi-io/odoo/refs/heads/19.0/README.md
    filename: odoo_readme.md
    destination: readme_examples

  - type: http
    url: https://raw.githubusercontent.com/adomi-io/listing-lab/refs/heads/master/README.md
    filename: listing_lab_readme.md
    destination: readme_examples

  - type: http
    url: https://raw.githubusercontent.com/atinux/nuxt-auth-utils/main/README.md
    filename: nuxt-auth-utils.md
    destination: nuxt-auth-utils